### ISSUE TITLE
[BUG] KotlinNullPointerException when api call returns 204 No Content with null response

### ISSUE THREAD

**Issue by solcott** [slackhq/EitherNet#16]
### Describe the bug

When I make an API call that returns a **204 No Content** and the response in null I get 

```
kotlin.KotlinNullPointerException: Response from com.mediciland.datacollector.android.data.network.block.BlockApis.getBlock was null but response body type was declared as non-null
        at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:43)
        at com.slack.eithernet.ApiResultCallAdapterFactory$ApiResultCallAdapter$adapt$1$enqueue$1.onResponse(ApiResult.kt:245)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
        at com.google.firebase.perf.network.InstrumentOkHttpEnqueueCallback.onResponse(InstrumentOkHttpEnqueueCallback.java:69)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](../CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### To Reproduce
The retrofit call is defined as 

```kotlin
  @DecodeErrorBody
  @GET("block/{blockId}")
  suspend fun get(@Path("blockId") blockId: Long): ApiResult<BlockDto?, ErrorDto>
```
### Expected behavior
As long as the the ApiResult response type is defined as nullable I would expect to not get a NPE

**Comment by ZacSweers** [comment]
This is a tricky case. I think we should try to support 204 responses in the future, but cannot right now for two reasons:
1. We can't tell that your `BlockDto?` type is nullable from java reflection alone (which is what retrofit uses)
2. Retrofit does not try converters for 204/205 response codes - https://github.com/square/retrofit/issues/2867

The second one requires addressing in Retrofit, because we are just passing on the body from retrofit directly back to it and it throws the KNPE on its own null response body. It only natively supports null response bodies for `Void` and `Unit` (where it ignores them), so you could file a feature request upstream to support nullable types somehow. Fair warning though that is likely not possible right now due to the first mentioned bullet. It would require either reading `@Nullable` type annotations or some degree of kotlin-reflect or kotlin metadata to properly parse the kotlin function signature.

You should either use `Unit` or change your API to use something other than 204/205 for now.

**Comment by ZacSweers** [comment]
Adding to this a bit more - you should follow this issue https://github.com/square/retrofit/issues/3075

**Comment by Kshitij09** [comment]
So currently there's no way we can handle 204 No content return type ?

**Comment by ZacSweers** [comment]
As explained at length in the comment above, no.
